### ISSUE TITLE
[Enhancement] Double click no vídeo abrir full screen

### ISSUE THREAD

**Issue by matheusvellone** [lucianopf/escritorio-pagarme#20]
Direto me pego dando double click no vídeo pra ir pra full screen.
Imagino que não sou o único :joy: 

Será que não dá pra capturar o evento de double click e fazer ficar full screen ? Vou tentar investigar isso. Se eu achar algo eu abro um PR :smile:

**Comment by lucianopf** [comment]
Boa hein!! 🤔 
Acho que da pra colocar um handler  de onClick no Jitsi sim, só tem que pensar direitinho na lógica do double click 🤔

**Comment by lucianopf** [comment]
Lutamos bastante desenvolvendo essa mas chegamos a conclusão que é mais fácil usar a hotkey já do Jitsi `S` do que de fato implementar toda lógica de propagação de eventos.

@matheusvellone procede? Podemos fechar essa issue?

**Comment by lucianopf** [comment]
Fechando issue por inatividade 😬

**Comment by matheusvellone** [comment]
Sim @lucianopf. O esforço todo não valeria a pena dado que temos a hotkey por padrão já
