### ISSUE TITLE
dados sensiveis

### ISSUE THREAD

**Issue by brunooomelo** [lucianopf/escritorio-pagarme#22]
estava fazendo uns testes aqui. 
renova as credenciais e/ou adiciona variáveis de ambientes.

https://github.com/lucianopf/escritorio-pagarme/blob/caa39474b294e24c22d0be66e30808c1066bfb93/src/services/firebase.js#L5-L11

![image](https://user-images.githubusercontent.com/12174318/61726912-ccfe9e00-ad48-11e9-94a5-9ff66e0c8124.png)

**Comment by lucianopf** [comment]
Cara, inicialmente MUITO massa que tu viu o projeto, sééério, to aqui felizão com isso! hahaha

Então, a parada é que o firebase na real é bem peculiar nesse assunto e a tal `apiKey` aí é pública, e difere da `secretKey` e causa bastante confusão 😬 

(Acredite eu já peguei projeto que tinha a public aberta e zero regras de acesso 🤦‍♂  hehehe)

Então o fato dessas credenciais estarem aí é pra de fato o usuário poder se conectar ao firebase no nosso "db" e o que realmente importa são as rules de acesso nesse DB, que tão [aqui](https://github.com/lucianopf/escritorio-pagarme/blob/master/database.rules.json) inclusive.

Essas regras precisam estar beeem afinadinhas pra que tudo role de boa mas se tiverem alinhadas essas credenciais abertas não devem representar um dano 😬 

Se tive qualquer dúvida é só perguntar mestre, sério!! hehehe

**Comment by lucianopf** [comment]
Fechando a issue por agora mas muito obrigado pela preocupação e que fique claro que achei MUITO irado tu entrar no projeto pra ver como ele funciona!
