### ISSUE TITLE
[Enhancement] Branch protection rules

### ISSUE THREAD

**Issue by allangrds** [lucianopf/escritorio-pagarme#36]
## Feature
- Master branch protection against  a direct push;
- PR need to have 1 approved review at least.

**Comment by allangrds** [comment]
@lucianopf

**Comment by lucianopf** [comment]
Opa, boa!! Valeu por levantar essa @allangrds !!

**Comment by lucianopf** [comment]
<img width="806" alt="Screen Shot 2019-08-01 at 21 04 13" src="https://user-images.githubusercontent.com/8251208/62334903-ee296200-b49f-11e9-942c-2efa94e4793f.png">

Valeu por lembrar mestre!
