### ISSUE TITLE
[Enhancement] Ordenar salas por quantidade de usuários

### ISSUE THREAD

**Issue by Thor99** [lucianopf/escritorio-pagarme#38]
# Descrição

Dado que a tendência é o número de salas crescer, poderíamos ordená-las baseado em se têm alguém na sala (poderia ordenar por quantidade de usuários). Com isso, a visualização se daria primeiro por salas que possuem gente, seguidas por salas vazias, tendo uma visualização mais rápida dos "assuntos" que estão ativos no momento.

**Comment by MatheusVellone** [comment]
Resolvido pelo PR #40
